name: dead-links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  md-dead-link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -alh
          cd jrb.nz.v3 || exit
          npm run build
      - uses: untitaker/hyperlink@0.2.0
        with:
          args: _site/ --check-anchors