name: dead-links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  md-dead-link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: AlexanderDokuchaev/md-dead-link-check@5b5641a92ec95d13a5b04927e0e11de5c3405298 # v1.3.0